workflows:
  ios-workflow:
    name: Build iOS app
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install Node.js dependencies
        script: |
          rm -rf node_modules
          rm package-lock.json
          npm install
          ls -R node_modules
      - name: List files in root directory
        script: |
          ls -R
      - name: Verify Node.js and Capacitor
        script: |
          node -v
          npm -v
          npm list @capacitor/core
          npm list @capacitor/ios
      - name: Verify Capacitor Installation
        script: |
          cd ios/App
          ls -R ../node_modules/@capacitor
      - name: Verify CocoaPods version
        script: |
          pod --version
      - name: Clean CocoaPods
        script: |
          cd ios/App
          pod deintegrate
          pod cache clean --all
      - name: Update CocoaPods
        script: |
          gem install cocoapods
          cd ios/App
          pod install --repo-update
      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release clean archive -archivePath $CM_BUILD_DIR/ios.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/ios.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
