workflows:
  ios-workflow:
    name: Build iOS app
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Clean CocoaPods
        script: |
          cd ios/App
          pod deintegrate
          pod cache clean --all
      - name: List files in node_modules/@capacitor/ios/scripts
        script: |
          cd ios/App
          ls -R node_modules/@capacitor/ios/scripts

      - name: List files in node_modules
        script: |
          cd ios/App
          ls -R node_modules/@capacitor/ios/scripts

      - name: Verify CocoaPods version
        script: |
          pod --version

      - name: List files in node_modules
        script: |
          cd ios/App
          ls -R node_modules/@capacitor/ios/scripts

      - name: Update CocoaPods
        script: |
          gem install cocoapods
          cd ios/App
          pod deintegrate
          pod cache clean --all
          pod install --repo-update


      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release clean archive -archivePath $CM_BUILD_DIR/ios.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/ios.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
