workflows:
  ios-workflow:
    name: Build iOS app
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install Node.js dependencies
        script: |
          rm -rf node_modules
          rm package-lock.json
          npm install
      - name: List files in node_modules/@capacitor/ios/scripts
        script: |
          ls -R node_modules/@capacitor/ios/scripts
      - name: Verify CocoaPods version
        script: |
          pod --version
      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release clean archive -archivePath $CM_BUILD_DIR/ios.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/ios.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
